### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ocefpaf** [iuryt/ocean#1]
@iuryt Choose a license for you project.  I recommend [MIT](http://opensource.org/licenses/MIT) or BSD-like ([2](http://opensource.org/licenses/BSD-2-Clause) or [3](http://opensource.org/licenses/BSD-3-Clause) Clauses) licenses.

[Here](https://github.com/pyoceans/utilities/blob/master/LICENSE.txt) is a typical MIT licenses (automatically generated by GitHub BTW).

**Comment by iuryt** [comment]
It's done. Thanks for the help.
