### ISSUE TITLE
Thinking of the return of the "utils" module

### ISSUE THREAD

**Issue by dantecn** [iuryt/ocean#5]
I liked the idea of simplifying and making OceanLab more direct and specific. But I missed the old utils module, where you could get e.g. argdistnear easily. Why not come up with something like "tools" or "support" and bring back some of the "utils"?

**Comment by iuryt** [comment]
I can take a look later, but either @Ryukamusa or you can also try to do it if have some time.

**Comment by dantecn** [comment]
I'm just not sure yet where and how to add it.
I'm adding two new functions to OceanLab.dyn, which I will push soon to the project
